cpu               = "512"
memory            = "1024"
desired_count     = "0"
cluster_name      = "ai-app-cluster"
health_check_path = "/"
domain_name       = ""
subdomain         = "tm"
zone_id           = ""
zone_name         = ""
region_id         = "eu-north-1"

