cpu               = "512"
memory            = "1024"
desired_count     = "1"
cluster_name      = "ai-app-cluster"
health_check_path = "/"
domain_name       = "moyusufs-aiapp.com"
subdomain         = "tm"
zone_id           = "2924102a8b042443c2ed5abf025baf2f"
zone_name         = "moyusufs-aiapp.com"
region_id         = "eu-north-1"

