cpu               = "512"
memory            = "1024"
desired_count     = "0"
cluster_name      = "ai-app-cluster"
health_check_path = "/"
domain_name       = ""
subdomain         = "tm"
zone_id           = ""

image_id = "592587463331.dkr.ecr.eu-north-1.amazonaws.com/ai-app:v1"
