name: import temporary

on:
  workflow_dispatch:

jobs:

  terraform-apply:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Credentials for AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./Infra
        run: terraform init

      - name: Terraform import
        working-directory: ./Infra
        run: |
          terraform import module.ecs.aws_secretsmanager_secret.openai_api_key ai-app/openai-api-key \
          -target=module.ecr \
          --auto-approve \
          -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -var="openai_api_key=${{ secrets.openai_api_key }}" \
          -var="image_id=bootstrap"

