name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Credentials for AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t ai-app:v1 .

      - name: Tag Docker Image
        run: |
          docker tag ai-app:v1 \
          592587463331.dkr.ecr.eu-north-1.amazonaws.com/ai-app:v1

      - name: Push Docker Image
        run: |
          docker push \
          592587463331.dkr.ecr.eu-north-1.amazonaws.com/ai-app:v1